$name = "Lab03"

Vagrant.configure("2") do |config|

  config.vm.define "#$name"
  config.vm.box = "generic/ubuntu1804"

  config.vm.provider :qemu do |qe|
    qe.arch = "x86_64"
    qe.machine = "q35"
    qe.cpu = "max"
    qe.net_device = "virtio-net-pci"
  end

  config.vm.provider :virtualbox do |vb|
    vb.name = "SVEM_" + "#$name"
  end

  if Vagrant.has_plugin?("vagrant-qemu")
    puts "\e[1m-------------------------- QEMU --------------------------\e[0m"    
    config.vm.synced_folder "./lab", "/home/vagrant/lab", type: "rsync"
  else
    puts "\e[1m----------------------- VIRTUALBOX -----------------------\e[0m"
    config.vm.synced_folder "./lab", "/home/vagrant/lab"
  end
 
  if Vagrant::Util::Platform.darwin?
    config.vm.provision "shell", inline: "echo 'Network configuration for MacOS hosts'"
    config.vm.provision "file", source: "/etc/resolv.conf", destination: "/tmp/resolv.conf"
    config.vm.provision "shell", inline: "mv /tmp/resolv.conf /etc/resolv.conf"
  end 

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y vim gcc gdb
    apt-get install -y nasm
  SHELL
end
